### ISSUE TITLE
preset-type-definitions: create new preset for libs that wanna ship js types TS/Flow

### ISSUE THREAD

**Issue by Hotell** [treshugart/conartist#11]
as discussed here https://github.com/skatejs/renderer-preact/pull/3#issuecomment-332899826

it could be probably good idea to create presets for lib authors that don't use TS/Flow but wanna ship type definitions to their users

preset usage could look something like

```js
preset.typeDefinitions() // this would create structure etc for both typescript and flow
preset.typeDefinitions('typescript') // just TS
preset.typeDefinitions('flow') // just Flow
```

**Comment by treshugart** [comment]
I've removed presets from the core as I don't think it should have an opinion.
