### ISSUE TITLE
Some feature requests

### ISSUE THREAD

**Issue by Blasz** [treshugart/conartist#16]
Some potential feature requests, as discussed:

* Turn cwd flag arg into a rest arg, elevates the importance of the arg, less chars and allows specifying multiple paths easily
* Maybe pass basename of the cwd as an option somewhere, its used in quite a lot of places (e.g. package.json, any files that are named after the directory they reside in).
* Global overwrite flag/option
* Explicit undefined check on data to allow empty string data to still write the file
* Maybe make file deletions explicit with a field rather than specifying undefined?
* A QoL way to easily load config/data from an external file, either as raw data/string or function

Some others I thought of:
* Being able to nest the config file structure for subdirectories, currently we need to specify name as 'my-sub-dir/file.js'. It might be nice to be able to do something like:

```
const config = [
  {
    dir: 'my-sub-dir',
    files: [{
      { name: 'file.js', data: '...' },
    }]
  }
]
```

* conartist command to scaffold a conartist command :inception:

**Comment by treshugart** [comment]
> Turn cwd flag arg into a rest arg, elevates the importance of the arg, less chars and allows specifying multiple paths easily

👍 

> Maybe pass basename of the cwd as an option somewhere, its used in quite a lot of places (e.g. package.json, any files that are named after the directory they reside in).

I thought about this one on the way home and I think I'd like to let it soak a bit before implementing.

---

> Global overwrite flag/option

👍 I really like the idea of this, but as a top-level defaults spec for files. How deep should this go? Should it only apply to files at the level in which it is specified, or should it apply to all files in `includes` (might rename to `plugins` tbh)?

---

> Explicit undefined check on data to allow empty string data to still write the file

and

> Maybe make file deletions explicit with a field rather than specifying undefined?

I prefer the latter, I think.

---

> A QoL way to easily load config/data from an external file, either as raw data/string or function

I'll create a separate issue to flesh this out a bit more.

**Comment by treshugart** [comment]
I've created issues to track all of these separately. Thanks again for suggesting!
