### ISSUE TITLE
Alpha-order certain items

### ISSUE THREAD

**Issue by treshugart** [treshugart/conartist#6]
NPM will alpha-order dependency keys. We should do try and do this where it makes sense, if we can, to avoid unnecessary churn (such as in package.json dependencies).

**Comment by Hotell** [comment]
- https://www.npmjs.com/package/fixpack
- https://www.npmjs.com/package/sorted-object ( used [by npm](https://github.com/npm/npm/blob/latest/package.json#L107) )

**Comment by treshugart** [comment]
I've removed presets, so this probably doesn't need to be addressed anymore.
